build = { target = "riscv64gc-unknown-none-elf" }
[alias]
xtask = "run --target host-tuple --package xtask --"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -m 64M -s -nographic -kernel"
