[package]
name = "lunula"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lunula"
bench = false
test = true

[dependencies]
bitflags = "2.13.1"
critical-section = "1.2.0"
device_tree_parser = "0.4.0"
embedded-alloc = "0.7.0"
paste = "1.0.15"
qemu-exit = "4.0.0"
riscv = { version = "0.16.1", features = ["critical-section-single-hart", "s-mode"] }
sbi-rt = "0.0.4"
thiserror = { version = "2.0.19", default-features = false }
